### ISSUE TITLE
Vercel deployment isn't available

### ISSUE THREAD

**Issue by wolf-yuan-6115** [watercatuwu/CLHS-Gohan#1]
Vercel link on repo's homepage is not available anymore, it returns deployment not found error.

**Comment by watercatuwu** [comment]
This project is not loger maintained.
sorry :(

but I rewrite the UI and use Nuxt.js in another smilar project name [clhs-lunchv3](https://github.com/watercatuwu/clhs-lunchv3/)
it's still under development.

hopes it can help u
